### ISSUE TITLE
account not being created

### ISSUE THREAD

**Issue by johnmrncc1701d** [kinecosystem/kin-sdk-python#68]
I followed the instructions for creating an account but it is not working. It is giving me a pointer to an account but when I try to get the public address I get an empty string. And also the account is not saved so the next time I run it, it thinks there is not account yet. Here is my code snippet. Can you help with this? ty

        m_kinClient = new KinClient(Kin.Environment.Test, "1acd");
        if (!m_kinClient.HasAccount())
        {
            try
            {
                m_account = m_kinClient.AddAccount();
                //here account public address is ""
            }
            catch (KinException e)
            {
                m_lastException = e;
            }
        }
        else
        {
            m_account = m_kinClient.GetAccount(0);
        }

**Comment by Ronserruya** [comment]
> Sure you my move it. Just give me a link to the new location.
> How can I check if an account was already created from its public address?
> ty

There is a method for that: https://github.com/kinecosystem/kin-sdk-python/tree/v2-master#checking-if-an-account-exists-on-the-blockchain

**Comment by hitwill** [comment]
@johnmrncc1701d - This is what the problem is: You are trying to send Kin before calling:
account.create_account(address, starting_balance=amount, fee=minimum_fee, memo_text=id)

While in the Unity plugin, just sending Kin will create the account automatically for you, the python will require you to **explicitly** create the account first.

Let me know how it goes

**Comment by johnmrncc1701d** [comment]
I got it working, ty
