### ISSUE TITLE
record size (tx's /s) remains at ca 5-8 tx/s

### ISSUE THREAD

**Issue by TheBubblePopped** [kinecosystem/kin-sdk-python#88]
According to  kin-bubbles-heroku the Kin blockchain has more than what i get while using async for tx in client.somefunction():

I modified the values a bit but even with a higher record limit set to 100 i just get 10 records as response. Is this a limitation from the horizon server?

**Comment by Ronserruya** [comment]
Sorry but I didn't exactly understand the issue, can you share a code sample?

**Comment by TheBubblePopped** [comment]
No wonder, when looking at what i wrote. 
So let's assume a case in which i just listen to the whole network. Then i could use the horizon.transactions() function. There i can set in the funcvars the params dict with limit=int(higherthan10)  that alter the return size. 

Right now i am getting at every request 10~ records in each response batch. 

Imagine this code:

ssl = await client.horizon.transactions(sse=True, limit=100)
        async for tx in ssl:

Chaning the limit doesn't change the size of the returned records tho. I tried to calculate how many transactions i am getting per second but it's much lower than what https://kin-bubbles.herokuapp.com/ states on the upper corner left.

**Comment by swilso793** [comment]
Hi,

the way i see it the limit argument for the horizon.transactions function doesn't work correctly, or there is a central piece missing. Also directly calling the stellar backend api /transactions with SSE enabled always gives only 12 results per 10-15 seconds. Without SSE it works as expected.

**Comment by Ronserruya** [comment]
I see that issue now, after some tries, it looks like its a problem from the blockchain side (horizon), I'll forward it to them and keep you updated.

Btw, "limit" is not used when using SSE, since sse should constantly give all results one by one.

For the record, this is what I tried:

```python
from kin_base.horizon import Horizon, HORIZON_TEST, HORIZON_LIVE
import logging

async def main():

    async with Horizon(HORIZON_LIVE) as client:
        gen = await client.transactions(sse=True)
        async for tx in gen:
            pass # log

logging.basicConfig(level='DEBUG')
import asyncio
asyncio.run(main())
```

And I could see that I connect, get 10 results, and then the connection drops and I reset the SSE connection, and then it happens over and over again

**Comment by Ronserruya** [comment]
So I was wrong, there is a limit to SSE, and it was capped at 10. I will increase the limit to 200 (maximum), additionally, there was a bug with the last Id, so even after resetting we fetched the next ledger instead of continuing from where we left.

I opened a PR to the SSE package I use to fix it, once its merged I will add the necessary changes in the sdk itself.

Feel free to :+1: the PR :)

https://github.com/rtfol/aiohttp-sse-client/pull/3
